Qt Creator: Fix download of documentation for Qt 6
In Qt 6 there is a qt5-documentation.zip that contains all the html and
index files. The contents conflict with the contents of the other zip
files:

  Error: Destination path
  '.../qtdocumentation/tqtc-qt5-documentation/qdoc' already exists

If we find this file, just use it instead of all the others.

Change-Id: I0c65493e8eb9685e0c5124b8e9ffa36624b09895
Reviewed-by: Eike Ziller <eike.ziller@qt.io>